- name: install node packages
  npm: path={{ source_root }}/{{ app_name }} state=present

- name: uninstall global packages
  npm: name={{item}} state=absent global=yes
  with_items:
    - nodemon
    - eslint-config-airbnb
    - eslint-plugin-import
    - eslint-plugin-react
    - eslint-plugin-jsx-a11y
    - eslint
    - sequelize-cli
    - bcrypt
    - node-gyp
    - slug

# FIX: bcrypt, node-gyp, and slug should not be global. 
- name: install global packages
  npm: name={{item}} state=present global=yes
  with_items:
    - nodemon
    - eslint
    - eslint-plugin-import
    - eslint-plugin-react
    - eslint-plugin-jsx-a11y
    - eslint-config-airbnb
    - sequelize-cli
    - bcrypt
    - node-gyp
    - slug
